### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kazma258** [kamiya10/EDGEserver#2]
**敘述問題**
清楚的敘述問題
自動清理會清掉漏斗礦車

**重製問題**
重製出問題的步驟:
1. 
2. 

**預期行為**
敘述你預期會發生的事情

**螢幕截圖**
如果能，請附上截圖來讓我們更了解問題點

**備註**
跟這個問題有關的備註

**Comment by kamiya10** [comment]
寫個標題rrr

**Comment by kamiya10** [comment]
已解決
