### ISSUE TITLE
[BUG]水流不流動

### ISSUE THREAD

**Issue by kazma258** [kamiya10/EDGEserver#3]
**敘述問題**
清楚的敘述問題
水不會流動啊QQ

**重製問題**
重製出問題的步驟:
1. 
2. 

**預期行為**
敘述你預期會發生的事情

**螢幕截圖**
如果能，請附上截圖來讓我們更了解問題點

**備註**
跟這個問題有關的備註

**Comment by kamiya10** [comment]
明天處理
重製問題沒寫=3=

**Comment by kamiya10** [comment]
半夜的重開修好了一切
