### ISSUE TITLE
[BUG]普通玩家的領地上限

### ISSUE THREAD

**Issue by lewis252310** [kamiya10/EDGEserver#6]
**敘述問題**
普通玩家的領地上限只有32*32

**重製問題**
N/A

**預期行為**
建議增加普通玩家可圈選的領地上限

**螢幕截圖**
N/A

**備註**
這應該不算BUG (吧?

**Comment by kamiya10** [comment]
建議類請寫在Pull Request

**Comment by kamiya10** [comment]
算惹owo

**Comment by kamiya10** [comment]
fixed
